// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApP5mztKMvIC5guFqAdYx6llxlb_TwYDs',
    appId: '1:154470161714:web:72a1b1fc5a2d5a76e88b2b',
    messagingSenderId: '154470161714',
    projectId: 'anagkazo-sms',
    authDomain: 'anagkazo-sms.firebaseapp.com',
    storageBucket: 'anagkazo-sms.appspot.com',
    measurementId: 'G-42LE5V3VFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYosl1lSA1m9jNwEmgW-jCLMOmfh9FVag',
    appId: '1:154470161714:android:3b9b47ef551e640ee88b2b',
    messagingSenderId: '154470161714',
    projectId: 'anagkazo-sms',
    storageBucket: 'anagkazo-sms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTO8LQfa-3_Od5pwy3qQSxxSDhBhR2bsA',
    appId: '1:154470161714:ios:e4a9762887a9cd40e88b2b',
    messagingSenderId: '154470161714',
    projectId: 'anagkazo-sms',
    storageBucket: 'anagkazo-sms.appspot.com',
    iosClientId: '154470161714-gqctc554q2311bojgedamea1uc67qlg8.apps.googleusercontent.com',
    iosBundleId: 'com.anagkazosms.ta',
  );
}
